# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Destination root (/ is used if empty) 
DESTDIR ?= 

# Compiler flags to link shared library 
LINK_DLL_FLAGS ?= -shared

# C compiler 
CC = gcc

# Standard flags for CC 
CFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
AUTO_TAG_GEN_CFLAGS =   -fPIC -DPIC $(CPPFLAGS) $(CFLAGS)
AUTO_TAG_GEN_OBJECTS =  \
	auto_tag_gen_cmdline_ctags.o

### Conditionally set variables: ###



### Targets: ###

all: libauto_tag_gen.so

install: install_auto_tag_gen

uninstall: uninstall_auto_tag_gen

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f libauto_tag_gen.so
	rm -f libauto_tag_gen.so

libauto_tag_gen.so: $(AUTO_TAG_GEN_OBJECTS)
	$(CC) $(LINK_DLL_FLAGS) -fPIC -o $@ $(AUTO_TAG_GEN_OBJECTS)  $(LDFLAGS)

install_auto_tag_gen: libauto_tag_gen.so
	$(INSTALL) -d $(DESTDIR)~/.vim/plugin
	$(INSTALL) -m 644 libauto_tag_gen.so $(DESTDIR)~/.vim/plugin
	install -c libauto_tag_gen.so $(DESTDIR)~/.vim/plugin

uninstall_auto_tag_gen: 
	rm -f $(DESTDIR)~/.vim/plugin/libauto_tag_gen.so
	rm -f $(DESTDIR)~/.vim/plugin/libauto_tag_gen.so

auto_tag_gen_cmdline_ctags.o: ./cmdline_ctags.c
	$(CC) -c -o $@ $(AUTO_TAG_GEN_CFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_auto_tag_gen uninstall_auto_tag_gen


# Dependencies tracking:
-include ./*.d
